POST https://localhost:5001/v1/login HTTP/1.1
content-type: application/json

{
	"username": "robin",
	"password": "robin"
}

###

GET https://localhost:5001/v1/anonymous HTTP/1.1

###

GET https://localhost:5001/v1/authenticated HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJvYmluIiwicm9sZSI6ImVtcGxveWVlIiwibmJmIjoxNjM5MjY5MzEwLCJleHAiOjE2MzkyOTgxMTAsImlhdCI6MTYzOTI2OTMxMH0.rCKHf0kygM6dcJrtg0sEtqDxGSMQoPCj0poq5qOVXO4

###

GET https://localhost:5001/v1/employee HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJhdG1hbiIsInJvbGUiOiJtYW5hZ2VyIiwibmJmIjoxNjM5MjY5MTQ4LCJleHAiOjE2MzkyOTc5NDgsImlhdCI6MTYzOTI2OTE0OH0.JmByiVYzqi32pruPNPUTQzfYpxwJJbLPQt0-_Od59aQ

###

GET https://localhost:5001/v1/manager HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJvYmluIiwicm9sZSI6ImVtcGxveWVlIiwibmJmIjoxNjM5MjY5MzEwLCJleHAiOjE2MzkyOTgxMTAsImlhdCI6MTYzOTI2OTMxMH0.rCKHf0kygM6dcJrtg0sEtqDxGSMQoPCj0poq5qOVXO4

